/**
 * Shared SKU-generation helpers used by both the scraper (Phase 1 variant
 * creation) and the Shopify uploader (autoGenerateSku at upload time).
 *
 * The format is: `<PRODUCT_PREFIX>-<VARIANT_TOKEN>`
 *
 * PRODUCT_PREFIX
 *   - Derived from the product handle. Cleaned to uppercase A-Z 0-9 with
 *     single hyphens, capped at 8 chars.
 *   - If the handle is just `offer-<digits>` (auto-generated from a 1688 URL
 *     and not customer-meaningful), fall back to the first significant word
 *     of the product title — much more readable.
 *
 * VARIANT_TOKEN
 *   - Per variant: 3-4 char abbreviation per non-empty option value, joined
 *     by `-`. Each abbreviation strips non-alphanumeric, uppercases, takes
 *     the first 4 chars.
 *   - When NO option values are usable (single Default variant, or all
 *     options blank), fall back to the zero-padded position.
 *
 * DEDUPLICATION
 *   - `generateSkusForVariants` returns a Map<variantId, sku> with collisions
 *     resolved by appending `-2`, `-3`, etc. to the conflicting suffix.
 *
 * EXAMPLES
 *   handle="led", title=…              option1="Pink"                              → "LED-PINK"
 *   handle="usb-led", title=…          option1="Crystal Glass Walnut", option2="12W" → "USB-LED-CRYS-12W"
 *   handle="offer-1011758715713",
 *   title="Aluminum Touch Dimmable…"   option1=null                                → "ALUMI-01"
 *   handle="offer-884173459922",
 *   title="Woven Bamboo Wood…"         option1="EU Plug", option2="40W (No Light)" → "WOVEN-EUPL-40WN"
 */

const STOP_WORDS = new Set([
  "THE", "A", "AN", "AND", "OF", "FOR", "WITH", "IN", "ON", "TO", "OR",
]);

/** Strip everything except A-Z 0-9, uppercase, and take the first N chars. */
function alphaNumeric(s: string, max: number): string {
  return s.toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, max);
}

/**
 * Build a per-variant abbreviation from one option value.
 * - Multi-word: strip non-alphanumeric (collapse to one continuous string),
 *   take first 4 chars.
 * - Returns "" for null / empty input.
 */
function abbreviateOption(s: string | null | undefined): string {
  if (!s) return "";
  return alphaNumeric(s, 4);
}

/**
 * Pick the product-level prefix.
 *
 * If the handle is the auto-generated `offer-<digits>` form (from a 1688
 * URL like `detail.1688.com/offer/1011758715713.html`), it carries no
 * customer-meaningful information — use the first significant word of the
 * title instead. Otherwise the handle is the user's chosen identifier and
 * makes the cleanest prefix.
 */
export function deriveProductPrefix(handle: string | null, title: string): string {
  const cleanHandle = (handle || "").trim();
  const handleIsOfferAutoGenerated = /^offer-?\d+$/i.test(cleanHandle);
  if (cleanHandle && !handleIsOfferAutoGenerated) {
    // Use the handle, normalized and capped at 8 chars.
    return (
      cleanHandle
        .toUpperCase()
        .replace(/[^A-Z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .slice(0, 8) || "PROD"
    );
  }
  // Derive from the title's first significant word.
  const words = (title || "")
    .toUpperCase()
    .split(/\s+/)
    .map((w) => w.replace(/[^A-Z0-9]/g, ""))
    .filter((w) => w.length > 1 && !STOP_WORDS.has(w));
  if (words.length === 0) return "PROD";
  return words[0].slice(0, 5) || "PROD";
}

/**
 * Build the variant suffix from option1/2/3. Falls back to zero-padded
 * position when all options are blank.
 */
export function deriveVariantSuffix(
  options: Array<string | null | undefined>,
  position: number,
): string {
  const tokens = options.map(abbreviateOption).filter((s) => s.length > 0);
  if (tokens.length === 0) {
    return String(position + 1).padStart(2, "0");
  }
  return tokens.join("-");
}

/** Build a single SKU. The caller is responsible for collision detection. */
export function buildSku(
  handle: string | null,
  title: string,
  options: Array<string | null | undefined>,
  position: number,
): string {
  const prefix = deriveProductPrefix(handle, title);
  const suffix = deriveVariantSuffix(options, position);
  return `${prefix}-${suffix}`;
}

/**
 * Length of the cuid-derived unique tag appended to every SKU. Pulled from
 * the END of the variant cuid (cuids have higher entropy in the trailing
 * characters than the leading ones, which encode the timestamp/process).
 *
 * 6 alphanumeric chars = 36^6 ≈ 2.2 billion values — practically zero
 * collision risk at any realistic catalog size. Still readable.
 */
const UNIQUE_TAG_LENGTH = 6;

/**
 * Take the last N chars of a cuid (or any string), uppercased and stripped
 * to A-Z 0-9. Cuid trailing chars are the high-entropy counter; uppercasing
 * matches the rest of the SKU's style.
 */
export function uniqueTagFromId(id: string, len: number = UNIQUE_TAG_LENGTH): string {
  const cleaned = (id || "").toUpperCase().replace(/[^A-Z0-9]/g, "");
  return cleaned.slice(-len) || cleaned.padEnd(len, "0");
}

/**
 * Build a globally-unique SKU by appending a 6-char tag derived from the
 * variant's DB cuid. Guarantees that two variants — even with identical
 * handles, titles, and option values — will never collide.
 *
 * Use this whenever the variant's cuid is already known: in the uploader,
 * in any backfill script, and (via a post-insert update pass) in the
 * scraper. At scrape time the variant cuid only exists after `prisma.create`
 * returns — see the scraper's finalizeUniqueSkus helper.
 */
export function buildUniqueSku(
  handle: string | null,
  title: string,
  options: Array<string | null | undefined>,
  position: number,
  variantId: string,
): string {
  const base = buildSku(handle, title, options, position);
  const tag = uniqueTagFromId(variantId);
  return `${base}-${tag}`;
}

/**
 * Generate non-colliding SKUs for a full variant list of a single product.
 * Returns a Map keyed by some opaque variant id (caller picks — typically the
 * variant DB id, or just the index). Collisions are resolved by appending
 * `-2`, `-3`, etc. to the conflicting suffix.
 */
export function generateSkusForVariants<K>(
  handle: string | null,
  title: string,
  variants: Array<{
    key: K;
    option1?: string | null;
    option2?: string | null;
    option3?: string | null;
    position: number;
  }>,
): Map<K, string> {
  const prefix = deriveProductPrefix(handle, title);
  const out = new Map<K, string>();
  const suffixCounts = new Map<string, number>();
  for (const v of variants) {
    const baseSuffix = deriveVariantSuffix([v.option1, v.option2, v.option3], v.position);
    const seen = suffixCounts.get(baseSuffix) ?? 0;
    suffixCounts.set(baseSuffix, seen + 1);
    const finalSuffix = seen === 0 ? baseSuffix : `${baseSuffix}-${seen + 1}`;
    out.set(v.key, `${prefix}-${finalSuffix}`);
  }
  return out;
}
